require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot

AllCops:
  NewCops: disable

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/BlockComments:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false