require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot


Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/BlockComments:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false